language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mrdock/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrdock/docker-react npm run test

